name: Sync GitHub Issues to Google Sheet

on:
  issues:
    types: [opened]

jobs:
  sync-to-sheet:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Sync Issues
      - name: Sync Issues to Sheet
        uses: serban-petrescu/gh-issues-to-sheet@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          spreadsheet-id: "https://docs.google.com/spreadsheets/d/1XNNPGejfq-Tsd6RfbCYXyxOoA5ct6QmMyJQE0Dn8rv8/edit?usp=sharing"
          sheet-name: "Sheet1"
